### PR TITLE
Update jenkinsci repo with ElasticBox's latest changes 

### PR DESCRIPTION
**Pull request by gsanchezu**
In order to start creating PRs directly to jenkinsci repo

@oserna3, @osanjuan, 👍?

### CODE REVIEW

**Comment by gsanchezu** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build STARTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/36/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.0.50.2 and Jenkins instance at https://10.0.50.3

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/36/ for more details.

**Comment by oserna3** [comment]
good for me, ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-6ug8da, https://ops.elasticbox.com/services/instances/i-3rl6l6

**Pull request merged**
