### PR TITLE
[EBE-4205] Fix resource leak when failing provision

### PR DESCRIPTION
**Pull request by gsanchezu**
@jhita, review and update test, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.140.45.48 and Jenkins instance at https://10.0.48.135

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/44/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.140.45.48 and Jenkins instance at https://10.0.48.135

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/45/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.140.45.48 and Jenkins instance at https://10.0.48.135

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/46/ for more details.

**Comment by jhita** [comment]
Reviewed

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-wvigr7, https://ops.elasticbox.com/services/instances/i-8mmie7

**Pull request merged**
