### PR TITLE
Check maxCapacity against running pods

### PR DESCRIPTION
**Pull request by gsanchezu**
maxCapacity was checked against all existing pods, now just with running ones.

@DiegoSanjuan 👍 ?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/41/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please again

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.140.45.57 and Jenkins instance at https://10.0.48.81

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/42/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-mutrv6, https://ops.elasticbox.com/services/instances/i-y1d18t

**Pull request merged**
