### PR TITLE
Add proxy support to charts repo connection

### PR DESCRIPTION
**Pull request by gsanchezu**
@DiegoSanjuan, 👍 ?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.140.45.70 and Jenkins instance at https://10.0.48.145

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/43/ for more details.

**Comment by DiegoSanjuan** [comment]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-stt48g, https://elasticbox.com/services/instances/i-bw9qgq

**Pull request merged**
