### PR TITLE
Allow concurrent slaves for concurrent builds

### PR DESCRIPTION
**Pull request by gsanchezu**
@GustavoLlorente, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/47/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/48/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please 2

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/49/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please 3

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/50/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please 4, with updated settings.xml

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/51/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/52/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/53/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please again!

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/54/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please again 2!

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.166.246.28 and Jenkins instance at https://10.166.246.35

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/55/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/56/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/57/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.166.246.28 and Jenkins instance at https://10.166.246.35

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/58/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.166.246.28 and Jenkins instance at https://10.166.246.35

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See https://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/59/ for more details.

**Comment by GustavoLlorente** [comment]
ACK, the only thing is I'd like know how to launch this test to get involved with the environment

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-rsaiff, https://elasticbox.com/services/instances/i-q49x44, https://elasticbox.com/services/instances/i-y97yp2, https://ops.elasticbox.com/services/instances/i-kg2cvb

**Pull request merged**
